export const is = [
    "dreaming",
    "crying over spilled milk",
    "putting out fires",
    "eating life's lemons",
    "feeling good",
    "breaking things",
    '"insane"',
    "taking risks",
    "dying young as late as possible",
    "crossing tees and dotting eyes",
    "out of bubblegum",
    "never gonna give you up",
    "using his owl eyes",
    "forgetting something",
    "chasing the sun",
    "jumping for joy",
    "always learning",
    "on a journey",
    "on a roll",
    "doing flips",
    "climbing mountains",
    "taking flight",
    "defying gravity",
    "really cool",
    "working hard",
    "setting sail",
    "high on life",
    "geeking out",
    "rocking out",
    "helping out",
    "vibing out",
    "a goofball",
    "touching grass",
    "making friends",
    "making waves",
    "making peace",
    "petting the dog",
    "lost in thought",
    "charting waters",
    "locking in",
    "kickflippin",
    "flying too close to the sun",
    "tempting fate",
    "pushing luck",
    "living dangerously",
    "shooting at the stars",
    "finally free",
    "only going up",
];

export function onRequestGet(context) {
    return new Response("is " + is[Math.floor(Math.random() * is.length)], {
        headers: {
            "Content-Type": "text/plain",
        },
    });
}
